
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 936291
	#The name of the modpack
	modpackName = "Project: Boss RPG"
	#The version of the modpack
	modpackVersion = "v16r2"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = false

